#!/usr/bin/env bash

update_repo()
{
	NAME=$1
	REPO=$2
    BRANCH=$3
    
	if [ ! -d ${NAME} ]; then
        echo "Pulling ${NAME} FROM ${REPO} on branch ${BRANCH}"
        git clone ${REPO} ${NAME}
        cd ${NAME}
        git checkout $BRANCH
        cd ..
    else
        echo "Updating ${NAME} FROM ${REPO} on branch ${BRANCH}"
        cd ${NAME}
        git remote set-url origin $REPO
        git checkout $BRANCH
        echo ${NAME} `git pull`
        cd ..
	fi
}

while read comp; do
  if [ "$comp" != "" ]
  then 
    update_repo $comp &
  fi
done <databox-components

wait
