#!/bin/bash

#include helper functions
source ./scripts/utils.sh

## debug
if [[ "$DATABOX_DEBUG" = "true" ]]; then
  set -x
  PS4='$LINENO: '
fi

declare -r ME="$(basename $0)"

## check we have the tools
if ! [ -x "$(command -v docker)" ]; then
  die 1 "docker is not installed;"`
       `"see https://docs.docker.com/engine/installation/"
fi

if ! [ -x "$(command -v docker-compose)" ]; then
  die 2 "docker-compose is not installed;"`
       `"see https://docs.docker.com/compose/install/#install-compose"
fi

if [ "$1" == "sdk" ]
then
  docker-compose -f docker-databox-sdk.yaml down
  die 3 "SDK stoped."
fi

## stop Databox
err "stopping Databox ..."
docker stack rm databox
docker-compose -f ./docker-databox-appstore.yaml down

err "stopping and remvoing databox-bridge ..."
docker stop bridge >/dev/null 2>&1
docker rm bridge >/dev/null 2>&1
err "removing network databox-system-net ..."
docker network rm databox-system-net >/dev/null 2>&1

err "waiting ..."
sleep 10 # give docker some time to remove the networks etc
err "forcing ..."
docker swarm leave --force
err "done!"
