#!/bin/bash

set -e

## debug
if [[ "$DATABOX_DEBUG" = "true" ]]; then
  set -x
  PS4='$LINENO: '
fi

declare -r ME="$(basename $0)"
err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z') $ME]: $@" >&2
}
die() {
  rc=$1
  shift
  err "$@"
  exit $rc
}

## check we have the tools
if ! [ -x "$(command -v docker)" ]; then
  die 1 "docker is not installed;"`
       `"see https://docs.docker.com/engine/installation/"
fi

if ! [ -x "$(command -v docker-compose)" ]; then
  die 2 "docker-compose is not installed;"`
       `"see https://docs.docker.com/compose/install/#install-compose"
fi

## stop Databox
err "stopping Databox ..."
docker stack rm databox
err "waiting ..."
sleep 10 # give docker some time to remove the networks etc
err "forcing ..."
docker swarm leave --force
err "done!"
