FROM amd64/alpine:3.9.3 as build
MAINTAINER Anthony Brown <anthony.brown@nottingham.ac.uk>

RUN apk --no-cache add --update \
    alpine-sdk \
    build-base \
    git \
    go \
    libsodium-dev \
    libzmq \
    zeromq-dev

ENV GOPATH /

# RUN mkdir -p /src/github.com/docker \
#     && git -C /src/github.com/docker clone --depth 1 https://github.com/docker/docker

COPY *.go /
COPY Makefile Makefile
RUN make bin/databox

FROM amd64/alpine:3.9.3
RUN apk --no-cache add --update libzmq
COPY --from=build /bin/databox /databox
RUN mkdir -p /certs && mkdir -p /sdk
CMD ["/databox"]
