FROM amd64/alpine
RUN apk update && apk add build-base go git libzmq zeromq-dev alpine-sdk libsodium-dev

ENV GOPATH /

RUN go get -u github.com/pkg/errors
RUN go get -u github.com/pebbe/zmq4
RUN go get -u golang.org/x/net/proxy
RUN go get -u github.com/docker/go-connections/nat
RUN go get -u github.com/pkg/errors
RUN go get -u github.com/docker/docker/api/types
RUN go get -u github.com/docker/docker/client
RUN go get -u github.com/toshbrown/lib-go-databox
COPY . .

RUN make build