version: '3.1'

# Build and start the Databox platform

services:
#Build and satart the databox platform
    container-manager:
        build:
            context: ./core-container-manager
            dockerfile: Dockerfile${DATABOX_ARCH}
        image: ${DOCKER_REPO}container-manager
        ports:
            - '8989:8989'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './docker-compose.yaml:/cfg/docker-compose.yaml'
            - './src/config.json:/cfg/config.json'
            - './certs:/certs'
        environment:
            - 'DATABOX_ARBITER_ENDPOINT=https://arbiter:8080'
            - 'DATABOX_DEV=${DATABOX_DEV}'
            - 'DATABOX_SDK=${DATABOX_SDK}'
        networks:
            - databox-cm-arbiter-net
            - databox-cm-app-server-net
            - databox-driver-net
            - databox-app-net
        secrets:
            - DATABOX_ROOT_CA
            - CM_KEY
            - DATABOX_CM.pem
        depends_on:
            - arbiter
        deploy:
            replicas: 1
            placement:
                constraints:
                    - 'node.role == manager'

    arbiter:
        build:
            context: ./core-arbiter
            dockerfile: Dockerfile${DATABOX_ARCH}
        image: ${DOCKER_REPO}arbiter
        networks:
            - databox-cm-arbiter-net
            - databox-driver-net
            - databox-app-net
        secrets:
            - DATABOX_ROOT_CA
            - CM_KEY
            - DATABOX_ARBITER.pem
            - DATABOX_EXPORT_SERVICE_KEY
        deploy:
            replicas: 1
            placement:
                constraints:
                    - 'node.role == manager'

    export-service:
        build:
            context: ./core-export-service
            dockerfile: Dockerfile${DATABOX_ARCH}
        image: ${DOCKER_REPO}export-service
        depends_on:
            - arbiter
        environment:
            - 'DATABOX_ARBITER_ENDPOINT=https://arbiter:8080'
        networks:
            - databox-app-net
        secrets:
            - DATABOX_ROOT_CA
            - DATABOX_EXPORT_SERVICE_PEM.json
            - DATABOX_EXPORT_SERVICE.pem
            - DATABOX_EXPORT_SERVICE_KEY
        deploy:
            replicas: 1
            placement:
                constraints:
                - 'node.role == manager'

#Core apps and stores needed for testing
    store-json:
        build:
            context: ./store-json
            dockerfile: Dockerfile${DATABOX_ARCH}
        image: store-json

    store-timeseries:
        build:
            context: ./store-timeseries
            dockerfile: Dockerfile${DATABOX_ARCH}
        image: store-timeseries
    
    driver-os-monitor:
        build:
            context: ./driver-os-monitor
            dockerfile: Dockerfile${DATABOX_ARCH}
        image: driver-os-monitor
    app-os-monitor:
        build:
            context: ./app-os-monitor
            dockerfile: Dockerfile${DATABOX_ARCH}
        image: app-os-monitor
        
secrets:
  DATABOX_ROOT_CA:
    file: ./certs/containerManager.crt
  CM_KEY:
    file: ./certs/arbiterToken-container-manager
  DATABOX_CM.pem:
    file: ./certs/containerManager.pem
  DATABOX_ARBITER.pem:
    file: ./certs/arbiter.pem
  DATABOX_EXPORT_SERVICE_PEM.json:
    file: ./certs/export-service.json
  DATABOX_EXPORT_SERVICE.pem:
    file: ./certs/export-service.pem
  DATABOX_EXPORT_SERVICE_KEY:
    file: ./certs/arbiterToken-export-service

networks:
    databox-cm-arbiter-net:
        driver: overlay
    databox-cm-app-server-net:
        driver: overlay
    databox-driver-net:
        driver: overlay
    databox-app-net:
        driver: overlay
#    databox-cloud-net:
#        driver: overlay
