FROM amd64/alpine:3.8 as build
RUN echo http://nl.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
RUN apk update && apk add build-base go git libzmq zeromq-dev alpine-sdk libsodium-dev
RUN apk add 'go>=1.11-r0' --update-cache --repository http://nl.alpinelinux.org/alpine/edge/community

COPY *.go /
COPY *.mod /
#COPY *.sum /
COPY Makefile Makefile

RUN make build

FROM amd64/alpine:3.8
RUN apk update && apk add libzmq
COPY --from=build /bin/databox /databox
RUN mkdir -p /certs && mkdir -p /sdk
CMD ["/databox"]