version: '3.3'

services:
#start the databox platform
    container-manager:
        image: ${DOCKER_REPO}container-manager
        ports:
            - '8989:8989'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './docker-compose.yaml:/cfg/docker-compose.yaml'
            - './src/config.json:/cfg/config.json'
            - './certs:/certs'
            - './.resolv.conf:/etc/resolv.conf'
        environment:
            - 'DATABOX_ARBITER_ENDPOINT=https://arbiter:8080'
            - 'DATABOX_DEV=${DATABOX_DEV}'
            - 'DATABOX_SDK=${DATABOX_SDK}'
        networks:
#           - databox-cm-arbiter-net
            - databox-cm-app-server-net
#           - databox-driver-net
#           - databox-app-net
            - databox-system-net
        secrets:
            - DATABOX_ROOT_CA
            - CM_KEY
            - DATABOX_CM.pem
        depends_on:
            - arbiter
        deploy:
            replicas: 1
            placement:
                constraints:
                    - 'node.role == manager'

    arbiter:
        image: ${DOCKER_REPO}arbiter
        networks:
#           - databox-cm-arbiter-net
#           - databox-driver-net
#           - databox-app-net
            - databox-system-net
        secrets:
            - DATABOX_ROOT_CA
            - CM_KEY
            - DATABOX_ARBITER.pem
            - DATABOX_EXPORT_SERVICE_KEY
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            placement:
                constraints:
                    - 'node.role == manager'

    export-service:
        image: ${DOCKER_REPO}export-service
        depends_on:
            - arbiter
        environment:
            - 'DATABOX_ARBITER_ENDPOINT=https://arbiter:8080'
        networks:
#           - databox-app-net
            - databox-system-net
        secrets:
            - DATABOX_ROOT_CA
            - DATABOX_EXPORT_SERVICE_PEM.json
            - DATABOX_EXPORT_SERVICE.pem
            - DATABOX_EXPORT_SERVICE_KEY
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            placement:
                constraints:
                - 'node.role == manager'

secrets:
  DATABOX_ROOT_CA:
    file: ./certs/containerManager.crt
  CM_KEY:
    file: ./certs/arbiterToken-container-manager
  DATABOX_CM.pem:
    file: ./certs/containerManager.pem
  DATABOX_ARBITER.pem:
    file: ./certs/arbiter.pem
  DATABOX_EXPORT_SERVICE_PEM.json:
    file: ./certs/export-service.json
  DATABOX_EXPORT_SERVICE.pem:
    file: ./certs/export-service.pem
  DATABOX_EXPORT_SERVICE_KEY:
    file: ./certs/arbiterToken-export-service

networks:
    databox-system-net:
        external: true
#   databox-cm-arbiter-net:
#       driver: overlay
    databox-cm-app-server-net:
        driver: overlay
    databox-driver-net:
        driver: overlay
    databox-app-net:
        driver: overlay
#    databox-cloud-net:
#        driver: overlay
