version: '3.2'

services:
  databox-network:
    image: ${DOCKER_REPO}core-network
    networks:
      databox-system-net:
        aliases:
          - databox-network
    volumes:
      - './certs/arbiterToken-databox-network:/run/secrets/DATABOX_NETWORK_KEY'
      - './certs/databox-network.pem:/run/secrets/DATABOX_NETWORK.pem'
    cap_add:
      - NET_ADMIN

networks:
  databox-system-net:
    external: true
