#!/bin/bash


if ! [ -x "$(command -v docker)" ]; then
  echo 1 "docker is not installed see https://docs.docker.com/engine/installation/"
  exit 1
fi

DBOX_VER=$(<../../Version)

usage() {
  echo $#
  echo "Please invoke this script with the IP of the local registry you want to mirror to."
  echo "Usage: mirror [registry host name and port]"
  echo "Flags:"
  echo "-h     This help message"
  exit 1
}

if [[ $# < 1 ]] || [[ "$1" == "-h" ]]  # Must have more than 1 args.
then
  usage
fi

clone () {
    docker pull $1
    docker tag $1 $2
    docker push $2
}

clone databoxsystems/driver-os-monitor $1/driver-os-monitor
clone databoxsystems/driver-twitter $1/driver-twitter
clone databoxsystems/driver-sensingkit $1/driver-sensingkit
clone databoxsystems/app-light-graph $1/app-light-graph
clone databoxsystems/arbiter:${DBOX_VER} $1/arbiter:${DBOX_VER}
clone databoxsystems/container-manager:${DBOX_VER} $1/container-manager:${DBOX_VER}
clone databoxsystems/export-service:${DBOX_VER} $1/export-service:${DBOX_VER}
clone databoxsystems/app-server $1/app-server
clone databoxsystems/driver-google-takeout $1/driver-google-takeout
clone databoxsystems/app-twitter-sentiment $1/app-twitter-sentiment
clone databoxsystems/base-image-ocaml $1/base-image-ocaml
clone databoxsystems/driver-phillips-hue $1/driver-phillips-hue
clone databoxsystems/app-os-monitor $1/app-os-monitor
clone databoxsystems/driver-tplink-smart-plug $1/driver-tplink-smart-plug
clone node:alpine $1/node:alpine

clone tlodge/databox-redis $1/databox-redis
clone tlodge/databox-sdk $1/databox-sdk
clone tlodge/databox-test-server $1/databox-test-server
clone tlodge/databox-redis $1/databox-redis
clone tlodge/mongo $1/mongo
