#!/usr/bin/env bash

function red {
  echo "\033[0;31m${1}\033[0m"
}
function green {
  echo "\033[0;32m${1}\033[0m"
}

ME='databox-build-core'

function datef
{
  date +'%Y-%m-%dT%H:%M:%S%z'
}

log() {
  echo "[$(datef) $ME]: $@"
}

err() {
  echo "[$(datef) $ME]: $@" >&2
}

die() {
  rc=$1
  shift
  err "$@"
  exit $rc
}

assert_or_die() {
  if [[ "$1" != "$2" ]]
  then
    die 1 "ERROR: ${3}"
  fi
}

